### PR TITLE
0.3.1 release preparation

### PR DESCRIPTION
**Pull request by sbesson**
Proposes to releases the latest bug fixes (#9, #12 and #13) as `omero-cli-render:0.3.1`

Additionally ecdf7d2 includes the prototype to deploy tags to PyPI via Travis and secure environment variables as we have done for bio-formats-examples. In terms of workflow, this means the release process would be slightly simplified as follows:

- bump the `version` variable via commit/PR
- create a signed tag on the commit with the non development version and push to GitHub
- the Travis tag build should then build and upload to PyPI
- bump the `version` to the next development segment via commit/PR

Feedback welcome on this strategy as we could extend it to other Python modules.

### CODE REVIEW

**Comment by joshmoore** [comment]
Sounds good. Do you have a sample `git log --oneline --decorate` output from a repo following this strategy?

**Comment by sbesson** [comment]
Tried to deploy on testPypi - see https://travis-ci.org/sbesson/omero-cli-render/builds/427560610 and https://travis-ci.org/sbesson/omero-cli-render/builds/427575663. Getting authentication issues, I will try to debug further. Otherwise. I will drop  ecdf7d2  for now and get the release done.

**Comment by sbesson** [comment]
I did not manage to get  ecdf7d2  passing using `server: https://test.pypi.org/legacy` and my test credentials from a local tag - see https://travis-ci.org/sbesson/omero-cli-render/builds/427560610 for the typical 403 error I received. Closing this and I will release manually.

**Comment by jburel** [comment]
https://github.com/MicronOxford/webtagging/blob/master/autotag/release.py this was the approach not via travis

**Pull request closed without merging**
