### PR TITLE
Bump to 0.2 dev

### PR DESCRIPTION
**Pull request by joshmoore**
cc: @sbesson @jburel

### CODE REVIEW

**Comment by joshmoore** [comment]
Few different options here:

 * `0.2dev`
 * `0.2.dev`
 * `0.2-dev`
 * etc

**Comment by sbesson** [comment]
Sounds like the right moment to settle on our Python policy versioning policy - see also https://trello.com/c/yVOCHOtb/134-app-version-number-strategy.

We have definitely seen the downsides of not complying with PEP 440 especially when deploying to Python hosted repositories like PyPI or Ansible Galaxy. 

My current preference would go towards the following scheme which is both PEP440 AND semver compliant for public user-facing releases and PEP440 compliant for the rest. As the [PEP440 scheme](https://www.python.org/dev/peps/pep-0440/#developmental-releases) recommends the usage of `.devN` for developmental segments, it might be easier to stick to that scheme and prevent complicationt. 

This would mean the following cycle:

```
0.1.0 # Public release - semver compliant
0.2.dev1 or 0.2.0.dev1  # Development release
0.2.a1, 0.2.b1, 0.2.rc1  # If needed, alpha/beta/rcs that can be deployed to hosted repositories
0.2.0 # Public release - semver complaint
```

The order of resolution is defined as:

```
version.parse("0.1.0") < version.parse("0.2.0.dev1") < version.parse("0.2a1") < version.parse("0.2rc1") < version.parse("0.2.0")
True
```

In terms of `X.Y.devN` vs `X.Y.Z.devN`, very slight preference for the latter.

**Comment by joshmoore** [comment]
I prefer the latter as well, but I didn't think it was semver compliant, needing to be `X.Y.Z-devN`. Parsing through https://github.com/semver/semver/blob/master/semver.md#backusnaur-form-grammar-for-valid-semver-versions I wouldn't think so:

```
<valid semver> ::= <version core>
                 | <version core> "-" <pre-release>
                 | <version core> "+" <build>
                 | <version core> "-" <pre-release> "+" <build>
```

**Comment by joshmoore** [comment]
Discussing with @sbesson, there's likely not much we can do to _always_ be semver _and_ PEP440 compliant. I'm fine with either `0.2.0.dev1` or `0.2.dev1` (especially pre-1).

**Pull request merged**
