### PR TITLE
Don't start rendering engine to get settings

### PR DESCRIPTION
**Pull request by dominikl**
Load the rendering settings without creating a rendering engine.
Follow up on @jburel 's comment https://github.com/ome/omero-cli-render/pull/47#issuecomment-706019701 .

I've not replaced the `RenderObject` yet, just created `RenderObjectNoEngine` for now for easier comparison.
Two issues remaining:
- I don't know how to get the tile size, zoom levels, etc. info without the rendering engine. But is that actually necessary? Strictly speaking this is not a matter of the rendering settings.
- And I dont' know how to get the pixel min and max value. But again, is that necessary? I'm not 100% sure what that means, I assume that's the min and max value of the pixel type? So not really a "rendering" settings either.

### CODE REVIEW

**Comment by dominikl** [comment]
Actually also the fallback to create a rendering engine still needs to be there, in case the images doesn't have rendering settings yet.

**Comment by dominikl** [comment]
Ok, it's definitely not possible to get the min/max without calling the rendering engine's `getPixelsTypeLowerBound` method. And it's not necessarily just the min/max value of the pixel type. So the question is, do we really need this information in the render plugin? Same goes for zoom level, tile sizes, etc., do we really need them here? If so I can close the PR again and leave it with the previous behaviour, ie create a rendering engine for each image. /cc @jburel 
Btw, also found an old discussion about similar issue https://github.com/ome/openmicroscopy/pull/5476 .

**Comment by dominikl** [comment]
Ok, it's definitely not possible to get the min/max without calling the rendering engine's `getPixelsTypeLowerBound` method. And it's not necessarily just the min/max value of the pixel type. So the question is, do we really need this information in the render plugin? Same goes for zoom level, tile sizes, etc., do we really need them here? If so I can close the PR again and leave it with the current behaviour, ie create a rendering engine for each image. /cc @jburel 
Btw, also found an old discussion about similar issue https://github.com/ome/openmicroscopy/pull/5476 .

**Comment by jburel** [comment]
The methods ``getPixelsTypeLower/UpperBound`` were introduced b/c people wanted to in some cases render an image outside the min/max range for the viewed image and also we use them for settings interval when nothing is available. Let's discuss to be clear

**Comment by dominikl** [comment]
Discussion with @jburel : The min/max is calculated here: https://github.com/ome/omero-renderer/blob/c17065f519ae842378a1bebccb6c35fbeeba5da7/src/main/java/omeis/providers/re/metadata/StatsFactory.java#L222 . One option would be to make htis accessible in the API.

**Pull request closed without merging**
