### PR TITLE
Explicitly declare PyYAML as a dependency of omero-cli-render

### PR DESCRIPTION
**Pull request by sbesson**
Fixes https://github.com/ome/omero-cli-render/pull/27#issuecomment-465536107 /cc @pwalczysko

### CODE REVIEW

**Comment by pwalczysko** [comment]
Would this  mean that the error reported at pip install stage ("no  yaml")  would be supressed when this PR is merged and the plugin is released ?
Or would the pip automatically install yaml if not  installed with the omero-cli-render plugin ?

**Comment by sbesson** [comment]
The latter: `PyYAML` is a dependency from this Python module and should be installed during the `pip install` step.

It should be possible to test this PR in a fresh environment by running

```
pip install -e git+git://github.com/sbesson/omero-cli-render@PyYAML_dependency#egg=omero-cli-render
```

**Comment by pwalczysko** [comment]
```
Cloning git://github.com/sbesson/omero-cli-render (to PyYAML_dependency) to ./src/omero-cli-render
Collecting PyYAML (from omero-cli-render)
Installing collected packages: PyYAML, omero-cli-render
  Running setup.py develop for omero-cli-render
Successfully installed PyYAML-3.13 omero-cli-render
You are using pip version 9.0.3, however version 19.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by pwalczysko** [comment]
Test

Uninstall of PyYAML from my Mac, then verifying that the server starts with the error on the render.py plugin = negative test.

Uninstall the release cli-render plugin and then install the plugin from this PR. The resulting output indicates that the PyYAML was installed too as expected.

But, how do I run the plugin itself now ? ``bin/omero render -h`` gives nothing... What is the command please ?

**Comment by pwalczysko** [comment]
Ready to merge FMPOV

**Comment by sbesson** [comment]
Should now be released as https://pypi.org/project/omero-cli-render/0.4.2/

**Pull request merged**
