### PR TITLE
Add 'get' alias for 'info --style=json'

### PR DESCRIPTION
**Pull request by joshmoore**
see: https://forum.image.sc/t/omero-cli-render-get-function/60603/2

### CODE REVIEW

**Comment by sbesson** [comment]
💯  for the `get/set` symmetry. As this is expected an alias, should `get` also support all output formats but defaulting to `json` rather than `plain?

**Comment by dominikl** [comment]
I think it used to be `edit` and `info`, then we changed `edit` to `set`. Could even deprecate `info` and replace it with `get` in future?

**Comment by joshmoore** [comment]
Happy to defer on that, @dominikl. I can alternatively hide `info` as an undocumented alias so that it will continue to work for existing scripts (without a deprecation warning)

**Comment by dominikl** [comment]
No no, the alias looks good, happy to get this merged. Just in future we might also think about deprecating `info`. Just saw the `edit` command is still there too, although deprecated since ages.

**Comment by joshmoore** [comment]
Pushed an update.

**Comment by sbesson** [comment]
I assume this should be moved away from draft mode and marked as Ready for review?

**Comment by joshmoore** [comment]
Done.

**Review by sbesson — APPROVED** [review]
Should we get this released as 0.8.0? Anything else worth including?

**Comment by joshmoore** [comment]
Also :+1: for getting this in. Nothing else from my side.

**Pull request merged**
