### PR TITLE
Add batchset for rendering a folder of datasets

### PR DESCRIPTION
**Pull request by manics**
This is useful if all images in a dataset have the same renderdefs, but there are a lot of datasets:

1. Create a top-level directory
2. Under that directory create one directory per dataset with a name matching that of the dataset
3. In each of those directories create renderdef.yml with the rendering settings
4. Run `omero render batchset Project:<id> path/to/top-level/directory

Example: https://github.com/IDR/idr0071-feldman-crisprko/commit/5d41cd787a101a07f2f43e4d5343415d92f8c1d1 (private)

### CODE REVIEW

**Comment by joshmoore** [comment]
Generally nice idea! Did you also consider having all the renderdefs block in a single YAML which would allow using references & anchors?

**Comment by manics** [comment]
If there are no objections to defining `version: 3` of the format I can try it.

**Comment by sbesson** [comment]
Cross-linking to https://github.com/ome/omero-cli-render/issues/36 and https://github.com/IDR/idr0067-king-yeastmeiosis/tree/master/experimentA where a similar logic was required at the image level rather the dataset one. See also https://github.com/IDR/idr0040-aymoz-singlecell/tree/master/experimentA/rendering_settings for IDR precedents. As we have all implemented our own wrapping logic to handle this scenario, I am totally in favor of working towards a more generic way at the level of this repository.

A few comments:

- the name `renderdef.yml` feels a bit arbitrary but is descriptive enough. If we wanted flexibility, the filename could easily become an option of the `batchset` command. For comparison, `idr0067` used `<dataset name>.yml` which reduced this requirement
- thinking of the generalization of this extension step, I assume the logic could be further extended to images using `<dataset name>/<image name>/renderdef.yml`  or `<plate name>/renderdef.yml` for HCS in a second step?

**Comment by manics** [comment]
https://github.com/ome/omero-cli-render/pull/52 is a better solution since it avoids needing to escape filenames

**Pull request closed without merging**
